version: '#{build}'
image: 'Visual Studio 2022'
branches:
  only:
  - master
  - kptsky_testing
skip_tags: true
clone_depth: 1

environment:
  matrix:
   - configuration: x64
     BUILD_ARCH: x64
     BUILD_MSVC: msvc2022_64

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 17 2022" -A %BUILD_ARCH% -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_PREFIX_PATH=C:\Qt\6.9.3\%BUILD_MSVC% ..
  - cmake --build . --config Release

artifacts:
- path: build/build/Release/RcloneBrowser.exe

test: off
deploy: off
